#!/usr/bin/env python
#! encoding: utf-8
import requests
import sys

def getTrans(query, tl='en'):
  url="http://translate.google.com/translate_a/t"
  data={"client":"webapp", "sl":"auto", "tl":tl, "ie":"UTF-8", "oe":"UTF-8"}
  data['text'] = query
  headers={"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/22.0.1229.94 Safari/537.4"}
  r = requests.get(url, params=data, headers=headers)
  if 'sentences' in r.json:
    sentence = r.json['sentences'][0]
    print sentence['trans']

if __name__ == "__main__":
  if len(sys.argv) == 1:
    print "Usage: translate <phrase>"
  query = " ".join(sys.argv[1:])
  getTrans(query)
